sudo: false  # to use new infrastructure
language: java
cache:
  directories:
    - $HOME/.m2
#jdk:
#  - openjdk7
#  - oraclejdk8
install:
  - python -m virtualenv --system-site-packages ./venv && source venv/bin/activate && python -m pip install jsonschema && ./prepare-upload.sh
  - curl -vfk https://jmeter-plugins.org/unzip.php -F "zipfile=@upload/site.zip" -H "Authorization: Bearer $UPLOAD_TOKEN"
  - mvn -Dmaven.test.skip=true clean install --batch-mode
script:
  - mvn -Djava.awt.headless=true -Dmaven.test.redirectTestOutputToFile=true --fail-at-end --batch-mode org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report
after_success:
  - bash <(curl -s https://codecov.io/bash)
